version: "3.3"

services:
  nginx:
    container_name: yii2_ngnix
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config/yii2-test.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - yii-network

  pgsql:
    build:
      dockerfile: Dockerfile
      context: ./docker/pgsql
    restart: always
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "d3v"
      POSTGRES_DB: "unsplash"
    ports:
      - "5432:5432"
    volumes:
      - "./var/lib/pgdata:/var/lib/postgresql/data"
    container_name: yii2_pgsql
    networks:
      - yii-network

  php:
    container_name: yii2_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    depends_on:
      - pgsql
      - redis
    networks:
      - yii-network

  redis:
    build:
      dockerfile: Dockerfile
      context: ./docker/redis
    container_name: yii2_redis
    networks:
      - yii-network

  mail:
    container_name: yii2_mail
    build:
      dockerfile: Dockerfile
      context: ./docker/mailhog
    logging:
      driver: "none"
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web
    networks:
      - yii-network

networks:
  yii-network:
    driver: bridge
