version: "3.3"

services:
  nginx:
    depends_on:
      - pgsql
      - php
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx
    environment:
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "8081:80"
    volumes:
      - ./files:/var/www/html/
    container_name: yii2_ngnix
    networks:
      - yii-network

  pgsql:
    build:
      dockerfile: Dockerfile
      context: ./docker/pgsql
    restart: always
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "d3v"
      POSTGRES_DB: "unsplash"
    ports:
      - "5432:5432"
    volumes:
      - "./var/lib/pgdata:/var/lib/postgresql/data"
    container_name: yii2_pgsql
    networks:
      - yii-network

  php:
    depends_on:
      - redis
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./docker/php
      args:
        UID: 1000
        GID: 1000
    ports:
      - "9002:9000"
    volumes:
      - "./files:/var/www/html/"
    container_name: yii2_php
    networks:
      - yii-network

  redis:
    build:
        dockerfile: Dockerfile
        context: ./docker/redis
    container_name: yii2_redis
    networks:
      - yii-network
  
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - yii-network

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - yii-network

  mail:
    container_name: yii2_mail
    build:
        dockerfile: Dockerfile
        context: ./docker/mailhog
    logging:
        driver: 'none'
    ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web
    networks:
      - yii-network

networks:
  yii-network: 
    driver: bridge

